services:

  ############ modelcontextprotocolclient application ############
  modelcontextprotocolclient_application:
    image: openjdk:22-slim
    container_name: modelcontextprotocolclient-application
    working_dir: /app
    # For Linux: use network_mode: "host"
    network_mode: "host"
    # For Mac: Comment out network_mode: "host" above and uncomment these lines:
    # extra_hosts:
    #   - "localhost:192.168.65.2"
    ports:
      - 8080:8080
      - 5005:5005
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./local/root:/root
      # - ../ModelContextProtocolClient:/ModelContextProtocolClient # Use for local development
    tty: true

networks:
  app-network:
    driver: bridge